-- liquibase formatted sql
-- changeset Lucy:insertBebidasTable

INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Ninguna', 'Ninguna', 0, 9999, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Coca Cola', 'Coca Cola', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Inka Cola', 'Inka Cola', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Fanta', 'Fanta', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Sprite', 'Sprite', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Pepsi', 'Pepsi', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('7 Up', '7 Up', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Gatorade', 'Gatorade', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Powerade', 'Powerade', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Agua', 'Agua', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Agua con gas', 'Agua con gas', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Agua sin gas', 'Agua sin gas', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Cerveza Arequipeña', 'Cerveza Arequipeña', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Cerveza Pilsen', 'Cerveza Pilsen', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Cerveza Cristal', 'Cerveza Cristal', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Cerveza Cusqueña', 'Cerveza Cusqueña', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Cerveza Brahma', 'Cerveza Brahma', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Cerveza Corona', 'Cerveza Corona', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Cerveza Heineken', 'Cerveza Heineken', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Cerveza Budweiser', 'Cerveza Budweiser', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Mojito', 'Mojito', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Pisco Sour', 'Pisco Sour', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Chilcano', 'Chilcano', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Chicha Morada', 'Chicha Morada', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Chicha de Jora', 'Chicha de Jora', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Emoliente', 'Emoliente', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Mate de Coca', 'Mate de Coca', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Té', 'Té', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Café', 'Café', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Chocolate Caliente', 'Chocolate Caliente', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Chocolate Frío', 'Chocolate Frío', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche', 'Leche', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Chocolate', 'Leche con Chocolate', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Fresa', 'Leche con Fresa', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Plátano', 'Leche con Plátano', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Vainilla', 'Leche con Vainilla', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Canela', 'Leche con Canela', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Caramelo', 'Leche con Caramelo', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Miel', 'Leche con Miel', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Café', 'Leche con Café', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Té', 'Leche con Té', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Emoliente', 'Leche con Emoliente', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Mate de Coca', 'Leche con Mate de Coca', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Leche con Pisco Sour', 'Lecche con Pisco Sour', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Jugo de Naranja', 'Jugo de Naranja', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Jugo de Maracuyá', 'Jugo de Maracuyá', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Jugo de Fresa', 'Jugo de Fresa', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Jugo de Mango', 'Jugo de Mango', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Jugo de Piña', 'Jugo de Piña', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Jugo de Papaya', 'Jugo de Papaya', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Jugo de Manzana', 'Jugo de Manzana', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Baileys', 'Baileys', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vodka', 'Vodka', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Ron', 'Ron', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Whisky', 'Whisky', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Tequila', 'Tequila', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Pisco', 'Pisco', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Cognac', 'Cognac', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Gin', 'Gin', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Brandy', 'Brandy', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Licor de Café', 'Licor de Café', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Licor de Cacao', 'Licor de Cacao', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Licor de Menta', 'Licor de Menta', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Licor de Anís', 'Licor de Anís', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Licor de Durazno', 'Licor de Durazno', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Licor de Frambuesa', 'Licor de Frambuesa', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Sangría', 'Sangría', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Tinto', 'Vino Tinto', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Blanco', 'Vino Blanco', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Rosado', 'Vino Rosado', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Espumante', 'Vino Espumante', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Champagne', 'Vino Champagne', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Moscatel', 'Vino Moscatel', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Malbec', 'Vino Malbec', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Merlot', 'Vino Merlot', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Cabernet Sauvignon', 'Vino Cabernet Sauvignon', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Syrah', 'Vino Syrah', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Chardonnay', 'Vino Chardonnay', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Sauvignon Blanc', 'Vino Sauvignon Blanc', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Pinot Noir', 'Vino Pinot Noir', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Pinot Grigio', 'Vino Pinot Grigio', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Riesling', 'Vino Riesling', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Gewürztraminer', 'Vino Gewürztraminer', 5.00, 100, 4);
INSERT INTO delicias_rest.bebidas (nombre, descripcion, precio, stock, categorias_id) VALUES ('Vino Malvasía', 'Vino Malvasía', 5.00, 100, 4);